---
author: "Jacques van Helden"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    self_contained: no
    fig_caption: yes
    highlight: tango
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  ioslides_presentation:
    slide_level: 2
    self_contained: no
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    smaller: yes
    toc: yes
    widescreen: yes
  revealjs::revealjs_presentation:
    theme: night
    transition: none
    self_contained: true
    css: ../../slides.css
  slidy_presentation:
    smart: no
    slide_level: 2
    self_contained: yes
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    highlight: tango
    incremental: no
    keep_md: yes
    smaller: yes
    theme: cerulean
    toc: yes
    widescreen: yes
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  beamer_presentation:
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    incremental: no
    keep_tex: no
    slide_level: 2
    theme: Montpellier
    toc: yes
font-import: http://fonts.googleapis.com/css?family=Risque
title: PBM data analysis
subtitle: IBIS challenge 2024
font-family: Garamond
transition: linear
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE, echo=FALSE, eval=TRUE}
library(knitr)
library(kableExtra)
library(rprojroot)
# library(formattable)

root_dir = rprojroot::find_rstudio_root_file()
knitr::opts_knit$set(root.dir = root_dir)
#setwd(root_dir)

# options(encoding = 'UTF-8')
knitr::opts_chunk$set(
  fig.width = 7, 
  fig.height = 5, 
  fig.path = 'figures/PBM_',
  fig.align = "center", 
  size = "tiny", 
  echo = TRUE, 
  eval = TRUE, 
  warning = FALSE, 
  message = FALSE, 
  results = TRUE, 
  root.dir = root_dir,
  comment = "")

options(scipen = 12) ## Max number of digits for non-scientific notation
# knitr::asis_output("\\footnotesize")

options(width = 300)
# options(encoding = 'UTF-8')

# getwd()
```

```{r param}
#### Define parameters ####
data_type <- "PBM"
board <- "train"

```


```{r load_metadata}
## Load metadata
metadata_file <- file.path("metadata", "leaderboard", paste0("TF_DATASET_", data_type, ".tsv"))
setwd(root_dir)
getwd()
metadata <- read.table(metadata_file, header = FALSE, sep="\t")
colnames(metadata) <- c("TF", "dataset", "size")

## Separate the two normalization methods for each experiment
norm_methods <- c("SD", "QNZS")
metadata$experiment <- metadata$dataset
for (m in norm_methods) {
  metadata$experiment <- sub(pattern = paste0(m, "_"), replacement = "", x = metadata$experiment)
}
TFS <- unique(metadata$TF)
datasets <- unique(metadata$dataset)
experiments <- unique(metadata$experiment)
```



```{r load_data}

## Initialise with the first experiment
exp <- experiments[1]
setwd(root_dir)
#### Load all the data ####
message("Loading PBM data")
pbm_data <- list()
for (i in 1:nrow(metadata)) {
  #### Load one dataset ####
  TF <- metadata[i, "TF"]
  dataset  <- metadata[i, "dataset"]
  experiment <- metadata[i, "experiment"]
  message("\tLoading data\tTF: ", TF, "; dataset: ", dataset, "; experiment: ", experiment)
  data_file <- file.path("data", "leaderboard", board, "PBM", TF, paste0(dataset, ".tsv"))
  pbm_data[[dataset]] <- read.table(data_file, header = TRUE, sep = "\t", comment.char = "")
  names(pbm_data[[dataset]])[1] <- sub(pattern = "X.", replacement = "", x = names(pbm_data[[dataset]])[1])
  
  ## Sort dataset by spot ID
  spot_IDs <- pbm_data[[dataset]]$id_spot
  pbm_data[[dataset]] <- pbm_data[[dataset]][order(spot_IDs),]
  row.names(pbm_data[[dataset]]) <- pbm_data[[dataset]]$id_spot
  # dim(pbm_data[[dataset]])

}

# View(pbm_data)
# View(pbm_data[[1]])

```

## Signal intensities 

### Impact of normalization method (SD vs QNZS)

```{r SD_vs_QNZS, fig.width=10, fig.height=10, out.width="100%", fig.cap="Comparison of mean signal intensities between normalisation methods SD and QNZS. "}

#### Analyse distribution of signal ####

experiment <- experiments[1]

par(mfrow=c(2,2))

for (experiment in experiments) {
  
  TF <- unique(metadata[metadata$experiment == experiment, "TF"])
  
  SD <- pbm_data[[paste0("SD_", experiment)]]
  QNZS <- pbm_data[[paste0("QNZS_", experiment)]]
  spot_IDs <- sort(unique(c(SD$id_spot, QNZS$id_spot)))
  
  ## Make sure the two datasets have the same spot IDS
  SD <- SD[spot_IDs, ]
  QNZS <- QNZS[spot_IDs, ]
  
  ## Check that the PBM sequence is the same between SD and QNZS datasets
  table(SD$pbm_sequence == QNZS$pbm_sequence)
  
  ## Compare signal between normalisation methods
  plot(SD$mean_signal_intensity, QNZS$mean_signal_intensity,
       main = paste(TF, experiment),
       xlab = "SD signal (log scale)",
       ylab = "QNZS signal",
       log="x",
       col="#0044FF",
       panel.first = grid(col= "#888888"))
}
par(mfrow=c(1,1))


```



## Distribution of signal intenties

```{r signal_distrib_SD, fig.width=15, fig.height=10, out.width="100%", fig.cap="Distribution of mean signal intensities. "}
#### Plot the distribution of mean signal intensities ####


experiment <- experiments[1]

par(mfrow=c(4,2))

for (experiment in experiments) {
  
  TF <- unique(metadata[metadata$experiment == experiment, "TF"])
  
  SD <- pbm_data[[paste0("SD_", experiment)]]
  QNZS <- pbm_data[[paste0("QNZS_", experiment)]]
  spot_IDs <- sort(unique(c(SD$id_spot, QNZS$id_spot)))
  
  ## Make sure the two datasets have the same spot IDS
  SD <- SD[spot_IDs, ]
  QNZS <- QNZS[spot_IDs, ]

  
  SD_q95 <- quantile(x = SD$mean_signal_intensity, probs = 0.95, na.rm = TRUE)
  QNZS_q95 <- quantile(x = SD$mean_signal_intensity, probs = 0.95, na.rm = TRUE)
  
  
  ## Compare signal between normalisation methods
  hist(SD$mean_signal_intensity, breaks=1000, xlim=c(0,SD_q95),
       main=paste(TF, experiment, "SD signal"))
  hist(log(SD$mean_signal_intensity), breaks=1000, xlim=c(1,log(SD_q95)),
       main=paste(TF, experiment, "SD log(signal)"))
}
par(mfrow=c(1,1))


```

