## Test configuration for HTS data
EXPERIMENT=HTS
ifeq (${BOARD},final)
	DATASET=CREB3L3_R0_C1_lf5ACGACGCTCTTCCGATCTGA_rf3GGTCATAGATCGGAAGAGCA
#	TF=CREB3L3
else
	DATASET=NFKB1_R0_C1_lf5ACGACGCTCTTCCGATCTAC_rf3GCTGCTAGATCGGAAGAGCA
#	TF=NFKB1
endif
SOURCE_FORMAT=fastq
SOURCE_EXT=fastq.gz
